spring:
  application:
    name: demo

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'

xtb:
  serverEnum: DEMO
  subscribePrices:
    - USDTRY
    - US100
  topicName: "xtb.tickRecord"

